### ISSUE TITLE
An alternate way of getting data

### ISSUE THREAD

**Issue by cjyabraham** [DojoBits/cncf-kubestronauts#1]
Just wanted to mention that instead of scraping the data from the web page, you could import the data from [this file](https://github.com/cncf/people/blob/main/people.json) and filter on "category": "Kubestronaut". That is the central source for all the data on [the Kubestronaut webpage](https://www.cncf.io/training/kubestronaut/).

**Comment by vhristev** [comment]
I included people.json in my first README edition but removed it to keep it clean. When I found it, the script was already ready using Selenium. It was not worth the effort to change it. In general, people.json is the best way to do this. 

Thank you.

**Comment by vhristev** [comment]
README is updated according to your recommendations.
